// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkG_CYOEZ7f7HeP31XlOrE0I-M2fINnjk',
    appId: '1:515485543684:web:3f8016707f0bcc7b6cb451',
    messagingSenderId: '515485543684',
    projectId: 'simple-khata',
    authDomain: 'simple-khata.firebaseapp.com',
    storageBucket: 'simple-khata.appspot.com',
    measurementId: 'G-VG4L120G3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsMHx0MpFiAFOFNoyssEh6Fg_iR_oze5M',
    appId: '1:515485543684:android:60f92457aa079de66cb451',
    messagingSenderId: '515485543684',
    projectId: 'simple-khata',
    storageBucket: 'simple-khata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJbBeLol8t8fQ3JFybwuysGgppWkvl7w',
    appId: '1:515485543684:ios:6cdb1a2e3443b54f6cb451',
    messagingSenderId: '515485543684',
    projectId: 'simple-khata',
    storageBucket: 'simple-khata.appspot.com',
    iosClientId: '515485543684-agvadnp4k9tl32gpvh1uivq2167cnttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleKhata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwJbBeLol8t8fQ3JFybwuysGgppWkvl7w',
    appId: '1:515485543684:ios:6cdb1a2e3443b54f6cb451',
    messagingSenderId: '515485543684',
    projectId: 'simple-khata',
    storageBucket: 'simple-khata.appspot.com',
    iosClientId: '515485543684-agvadnp4k9tl32gpvh1uivq2167cnttu.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleKhata',
  );
}
